# Introduction
---
- A linear equation in the $n$ variables is an equation that can be written in the form: $a_1x_1+a_2x_2+...+a_nx_n = b$.
- $[a_1, ...,a_n]$ are called the coefficients of the equation, while $b$ is called the constant term.
- Recall the general equation of a line in $\mathbb{R}^2$ is $ax+by=c$.
- Recall the general equation of a plane in $\mathbb{R}^3$ is $ax+by+cz=d$.
#### Examples:
The following are linear quations:
- $3x-4y=1$
- $r-\frac{1}{2}s-\frac{3}{15}t=9$
- $x_1+5x_3 = 4x_2+7x_4$
- $\sqrt{\cos{\theta}} \ x+\frac{\pi}{4}y+(\sin{\frac{\pi}{2}})z=1$<br><br><br>
The following are not linear equations:
- $\sqrt{\cos{\theta}x}+\frac{\pi}{4}y+(\sin{\frac{\pi}{2}})z=1$
- $xy+2z=1$
- $3x^2+2x+2=1$

# System of Linear Equations
---
- A system of linear equations is a list of linear equations having the same unknowns.
- A linear equation can be denoted as $L$, if there are $n$ number of unknowns, then you will need $L_n$ numbers of linear equations.
- A system of linear equation can be written in the standard form as:
\begin{equation}
a_{11}x_{1}+a_{12}x_{2}+a_{13}x_{3}+...+a_{1n}x_{n} = b_1 \\
a_{21}x_{1}+a_{22}x_{2}+a_{23}x_{3}+...+a_{2n}x_{n} = b_2 \\
a_{31}x_{1}+a_{32}x_{2}+a_{33}x_{3}+...+a_{3n}x_{n} = b_3 \\
............................................. \\
a_{n1}x_{1}+a_{n2}x_{2}+a_{n3}x_{3}+...+a_{nn}x_{n} = b_n \\
\end{equation}
**<font color=blue>$\to$</font>** Observe that the system of linear equations above has $n$ unknowns, that is $x_1$ to $x_n$, this means that we need $L_n$ number of linear equations to find the value of these unknowns.
- if $b_1 = b_2 = b_3 = ... = b_n =0$ then the system is said to be homogenous, otherwise it is nonhomogenous.
- The values of the unknown is called a solution, or a list of solutions.
- The system of linear equation can either be written as an augmented matrix, which is composed of the coefficient and the constant:
\begin{align}
\textbf{M} = \begin{bmatrix}
a_{11} \ a_{12} \ a_{13} \ ... \ a_{1n} \ |b_1 \\
a_{21} \ a_{22} \ a_{23} \ ... \ a_{2n} \ |b_2 \\
a_{31} \ a_{32} \ a_{33} \ ... \ a_{3n} \ |b_3 \\
............................................. \\
a_{n1} \ a_{n2} \ a_{n3} \ ... \ a_{nn} \ |b_n \\
\end{bmatrix}
\end{align}<br>
- or it can be represented as a coefficient matrix, which is composed of the coefficient only:
\begin{align}
\textbf{A} = \begin{bmatrix}
a_{11} \ a_{12} \ a_{13} \ ... \ a_{1n} \\
a_{21} \ a_{22} \ a_{23} \ ... \ a_{2n} \\
a_{31} \ a_{32} \ a_{33} \ ... \ a_{3n} \\
.......................................\\
a_{n1} \ a_{n2} \ a_{n3} \ ... \ a_{nn}  \\
\end{bmatrix}
\end{align}
<br>
<br>
**<font color=blue>$\to$</font>** If all the coefficient of a linear equation are zeroes then it is called a set of degenerate linear equation.

Solving a System of Linear Equation by Elimination
---
- Given an $L_n$ nunber of linear equations do:
1. Forward elimination: multiply each equation with a constant that result of the coefficients will be negative of each other.
2. Add the linear equations to obtain a new linear equation.
3. Perform a back substitution to solve for the unknowns.

### example:
Given two equations $L_1: 2x-3y=-8$ and $L_2: 3x+4y=-5$<br>
Solve for the unknowns $x$ and $y$:

\begin{align}
L_1 : 2x-3y =-8 \\
L_2 : 3x+4y =5 \\
\end{align}
<br>
<br>
$\to$ we first perform forward elimination to eliminate $x$ by multiplying -3 to $L_1$ and multiplying 2 to $L_2$: <br><br>
\begin{align}
-3L_1 : -3(2x-3y =-8) \\
2L_2 : 2(3x+4y =5) \\
\end{align}
<br>
<br>
\begin{align}
-3L_1 : -6x+9y =24) \\
2L_2 : 6x+8y =10) \\
\end{align}
<br>
<br>
$\to$ add $-3L_1$ and $2L_2$: <br><br>
\begin{align}
-3L_1+ 2L_2 : 17y =34
\end{align}
<br>
<br>
\begin{align}
\frac{17y}{17} =\frac{34}{17}
\end{align}
<br>
<br>
\begin{align}
\therefore y =2
\end{align}
<br>
<br>
$\to$ perform back substituion to get the value of $x$, choose weither $L_1$ or $L_2$, the answer will be the same:<br><br>
\begin{align}
2x-3(2) =-8 \\
\end{align}
<br>
<br>
\begin{align}
2x-6 =-8 \\
\end{align}
<br>
<br>
\begin{align}
2x =-8+6 \\
\end{align}
<br>
<br>
\begin{align}
2x =-2 \\
\end{align}
<br>
<br>
\begin{align}
x =-1 \\
\end{align}
<br>
<br>
\begin{align}
\therefore \ x=-1, y=2
\end{align}

# The Row Echelon Form as Preliminary for Gaussian Elimination
---
- A row echelon must satisfy the following conditions:
1. Any rows which are majority zeroes must be at the bottom.
2. In each non-zero row, the first nonzero entry (**leading entry**) is in a column to the left of the leading entry below it.
#### Examples:
- The following are proper row echelon format:
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 & 1  \\
           0 & -1  \\
         \end{bmatrix}
  \end{align}<br><br>
\begin{align}
    \textbf{B} = \begin{bmatrix}
           1 & 2 & 3  \\
           0 & -1 & 4  \\
           0 & 0 & 7  \\
         \end{bmatrix}
  \end{align}<br><br>
\begin{align}
    \textbf{C} = \begin{bmatrix}
           1 & 2 & 3 & 6  \\
           0 & -1 & 4  & -3 \\
           0 & 0 & 7 & 8  \\
           0 & 0 & 0 & 13  \\
         \end{bmatrix}
  \end{align}<br><br><br>

- Any given matrix can be transformed into the row echelon form by elementary row operations which includes:
    1. Interchanging any two rows.
    2. Multiplying or dividing any row with a nonzero constant.
    3. Adding or subtracting two consecutive rows.
- Row operation notation:
    - $R_i \leftrightarrow R_j$: interchange row i with row j.
    - $kR_i$: multiply a constant to row i.
    - $R_i + R_j$: add row j to row i, and replace row i with the result.
    - $R_i + kR_j$: add k times row j to row i and replace row i with the result.
- Row operation is the basis of row reduction.

#### Example
- Reduce the matrix:
$
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
2 & 4 & 0 & 0 & 2 \\
2 & 3 & 2 & 1 & 5 \\
-1 & 1 & 3 & 6 & 5 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2}-\text{2R}_{1},\text{R}_{3}-\text{2R}_{1}, \text{R}_{4} + \text{R}_{1}}
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & 0 & 8 & 8 & -8 \\
0 & -1 & 10 & 9 & -5 \\
0 & 3 & -1 & 2 & 10 \\
\end{bmatrix}
$
<br><br><br><br>
$
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & 0 & 8 & 8 & -8 \\
0 & -1 & 10 & 9 & -5 \\
0 & 3 & -1 & 2 & 10 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{3}}
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 8 & 8 & -8 \\
0 & 3 & -1 & 2 & 10 \\
\end{bmatrix}
$
<br><br><br>
$
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 8 & 8 & -8 \\
0 & 3 & -1 & 2 & 10 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} + 2\text{R}_{2}}
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 8 & 8 & -8 \\
0 & 0 & 29 & 29 & -5 \\
\end{bmatrix}
$
<br><br><br>
$
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 8 & 8 & -8 \\
0 & 0 & 29 & 29 & -5 \\
\end{bmatrix}
\xrightarrow{\frac{1}{8}\text{R}_{3}}
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 1 & 1 & -1 \\
0 & 0 & 29 & 29 & -5 \\
\end{bmatrix}
$
<br><br><br>
$
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 1 & 1 & -1 \\
0 & 0 & 29 & 29 & -5 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4}-29\text{R}_{3}}
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 1 & 1 & -1 \\
0 & 0 & 0 & 0 & 24 \\
\end{bmatrix}
$
<br><br><br><br>
- The row echelon form is:
\begin{bmatrix}
1 & 2 & -4 & -4 & 5 \\
0 & -1 & 10 & 9 & -5 \\
0 & 0 & 1 & 1 & -1 \\
0 & 0 & 0 & 0 & 24 \\
\end{bmatrix}
<br><br>
<font color=red>$\to$</font>: Two matrices $A$ and $B$ are row equivalent if there is a sequence of elementary row operations that can convert matrix $A$ to matrix $B$.

# Gaussian Elimination
---
- Solving linear equations by elimination is often applicable when the number of unknowns are manageable, however, when the number of unknown increases, the best way to solve it is via Gaussian elimination.
- Gaussian elimination is useful when handling the augmented matrix of the system of linear equations.
## Steps in Gaussian Elimination
---
1. Transform the system of linear equations to an augmented matrix.
2. Use the elementary row operations to reduce the augmented matrix to its row echelon forms.
3. Using back substitution, solve for the unknowns.
### Example
---
Solve the equation
$
\begin{equation}
2y+3z=8 \\
2x+3y+z = 5 \\
x-y-2z = -5
\end{equation}
$
<br><br>
$
\begin{pmatrix}
    0 & 2 & 3 &\bigm| & 8 \\
    2 & 3 & 1 &\bigm| & 5 \\
    1 & -1 & -2 &\bigm| & -5 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{3}}
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    2 & 3 & 1 &\bigm| & 5 \\
    0 & 2 & 3 &\bigm| & 8 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    2 & 3 & 1 &\bigm| & 5 \\
    0 & 2 & 3 &\bigm| & 8 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    0 & 5 & 5 &\bigm| & 15 \\
    0 & 2 & 3 &\bigm| & 8 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    0 & 5 & 5 &\bigm| & 15 \\
    0 & 2 & 3 &\bigm| & 8 \\
\end{pmatrix}
\xrightarrow{\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    0 & 1 & 1 &\bigm| & 3 \\
    0 & 2 & 3 &\bigm| & 8 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    0 & 1 & 1 &\bigm| & 3 \\
    0 & 2 & 3 &\bigm| & 8 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3}-2\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    0 & 1 & 1 &\bigm| & 3 \\
    0 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
$
<br><br>
- From the resulting augmented matrix, it can be shown that:
\begin{equation}
x-y-2z=-5 \\
y+z = 3 \\
z = 2
\end{equation}
- Performing back substitution, we can say that:
\begin{equation}
x-1-2(2)=-5 \leftrightarrow x-1-4 = -5 \leftrightarrow x-5 = -5 \leftrightarrow x=0\\
y+2 = 3 \leftrightarrow y=3-2 = 1\\
z = 2
\end{equation}
- the solution in vector form is:
\begin{pmatrix}
    0 \\
    1 \\
    2 \\
\end{pmatrix}

# The Rank of a Matrix
---
- The rank of a matrix is the number of nonzero rows in its row echelon form.
- Denoted as rank($\textbf{A}$).
- If a system of linear equations has $n$ variables, then the number of free variables can be determined by: $number \ free \ variables = n-rank(A)$.
#### Example:
---
- In the previous exercise, the final row echelon takes the form:
\begin{pmatrix}
    1 & -1 & -2 &\bigm| & -5 \\
    0 & 1 & 1 &\bigm| & 3 \\
    0 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
- There are three rows which are non-zeroes, so $rank(A)=3$. The number of variables is also $3$, because we have the unknowns: $x,y,z$, hence the $number \ free \ variables = n-rank(A)=3-3=0$.

# Reduced Row Echelon Form
---
- It is in the row echelon form.
- Unlike the row echelon form, which can have any values in the leading entry, in the reduced row echelon the leading entry must be 1 and zeroes anywhere.

# The Gauss Jordan Elimination
---
- While the Gaussian elimination is focused on utilizing the row echelon, the Gauss-Jordan utilizes the reduced row echelon.
- The Gauss-Jordan is useful for systems of linear equations with infinitely many solutions.
- The process:
    1. Write the augmented matrix of the system of linear equation.
    2. Use the elementary row operation to reduce the augmented matrix to reduced row echelon form.
    3. If the resulting system is consistent, transform the leading variables to 1.
#### Example:
---
Solve the equation
$
\begin{equation}
x+2y-z=3 \\
2x+3y+z = 1 \\
\end{equation}
$
**<font color=purple>$\to$</font>** observe that there are only two equations, $L_n = 2$, but three variables,$n=3$. Systems of linear solution where $L_n < n$ is an indicator of infinitely many solutions.
<br><br><br>
<br><br>
$
\begin{pmatrix}
    1 & 2 & -1 &\bigm| & 3 \\
    2 & 3 & 1 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -1 &\bigm| & 3 \\
    0 & -1 & 3 &\bigm| & -5 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & -1 &\bigm| & 3 \\
    0 & -1 & 3 &\bigm| & -5 \\
\end{pmatrix}
\xrightarrow[(-1)\text{R}_{2}]{\text{R}_{1} + 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 5 &\bigm| & -7 \\
    0 & 1 & -3 &\bigm| & 5 \\
\end{pmatrix}
$
<br><br>
- The final augmented matrix satisfies the definition of a reduced row echelon:
\begin{pmatrix}
    1 & 0 & 5 &\bigm| & -7 \\
    0 & 1 & -3 &\bigm| & 5 \\
\end{pmatrix}
<br>
- Replacing with the variables:
$
\begin{equation}
x+5z=-7 \\
y-3z = 5 \\
\end{equation}
$
- As expected, this system of linear equation can have an infinitely many solutions, to simplify this note that both equation has $z$ as the common variable, so the only thing we have control is the value of $z$.<br>
$
\begin{equation}
x=-7-5z \\
y = 5+3z \\
\end{equation}
$
- We can transform this into its vector format by letting $z = t$, to have the form:
$
\begin{pmatrix}
    x \\
    y \\
    z \\
\end{pmatrix}
=
\begin{pmatrix}
    -7 \\
    5 \\
    0 \\
\end{pmatrix}
+
t
\begin{pmatrix}
    -5 \\
    3 \\
    1 \\
\end{pmatrix}
$

# Linear Systems with No Solutions
---
- A linear system is said to have no solutions when the augmented matrix is inconsistent.
#### Example:
---
Solve the equation
$
\begin{equation}
x_1-x_2+2x_3=3 \\
x_1+2x_2-x_3 = -3 \\
2x_2-2x_3 = 1 \\
\end{equation}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 2 &\bigm| & 3 \\
    1 & 2 & -1 &\bigm| & -3 \\
    0 & 2 & -2 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 2 &\bigm| & 3 \\
    0 & 3 & -3 &\bigm| & -6 \\
    0 & 2 & -2 &\bigm| & 1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 2 &\bigm| & 3 \\
    0 & 3 & -3 &\bigm| & -6 \\
    0 & 2 & -2 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 2 &\bigm| & 3 \\
    0 & 1 & -1 &\bigm| & -2 \\
    0 & 2 & -2 &\bigm| & 1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 2 &\bigm| & 3 \\
    0 & 3 & -3 &\bigm| & -6 \\
    0 & 2 & -2 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3}-2\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 2 &\bigm| & 3 \\
    0 & 1 & -1 &\bigm| & -2 \\
    0 & 0 & 0 &\bigm| & 5 \\
\end{pmatrix}
$
<br><br>
- <font color=red>Notice the last row which is composed of zeroes but the corresponding constant has a value of 5 but we know that $0 \neq5$. Hence this is an inconsistent system of linear equation.

# The Homogenous Systems
---
- In previous discussion we have tackled systems of linear equations that can have either one of the following:
    1. A unique solution
    2. Infinitely many solutions
    3. No solutions or inconsistent.
    
- There are systems of linear equations that have atleast one solutions, and these are called homogenous systems.
- In a homogenous system, the constant term is zero.
- Therefore the augemented matrix of a homogenous system is $[\textbf{A}|0]$.
#### Example
---
\begin{equation}
2x+3y-z= 0 \\
-x+5y+2z = 0 \\
\end{equation}


In [9]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

# More Examples
---
Solve the equation
$
\begin{equation}
x_1-x_2+x_3=3 \\
2x_1+x_2+8x_3 = 18 \\
4x_1+2x_2-3x_3 = -2 \\
\end{equation}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    2 & 1 & 8 &\bigm| & 18 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3}-2\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{-1}{19}\text{R}_{3}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
$
<br><br>
The system of equation has the solution:
$
\begin{equation}
x_1-x_2+x_3=3 \\
x_2+2x_3 = 4 \\
x_3 = 2 \\
\end{equation}
$
<br>
Performing back substitution yields:
$
\begin{equation}
x_1-x_2+x_3=3 \to x_1-0+2 = 3 \to x_1 = 3-2 = 1 \\
x_2+2x_3 = 4 \to x_2+2(2)=4 \to x_2+4=4 \to x_2 = 4-4 =0 \\
x_3 = 2 \\
\end{equation}
$
<br>
$\therefore \ x_1=1, x_2=0, x_3=2$

In [21]:
# using pythonic solutions
import numpy as np
A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')
print("Use your assignment for the backward substitution to find the solutions.")

A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

Use your assignment for the backward substitution to find the solutions.


# Spanning Sets
---
- Recall that the linear equation has the form:
$a_1x_1+a_2x_2+...+a_nx_n=b$
- If we let $a_1,a_2,...,a_n$ be vectors, and $b$ is also a vector of the same size as the $a_1,a_2,...,a_n$.
- If we denotes $\{a_1,a_2,...,a_n\}$ as a set of vectors $\in \mathbb{R}^n$, then any linear combination of $\{a_1,a_2,...,a_n\}$ is called a **span** of $x_1,x_2,...,x_n$, which is denoted by $span(a_1,a_2,...,a_n)$
- If $span(a_1,a_2,...,a_n) \in \mathbb{R}^n$, then it is called the *spanning set* for $\mathbb{R}^n$.
#### Example:
Show that
\begin{pmatrix}
    \begin{bmatrix} 2 \\ -1 \end{bmatrix} \ 
    \begin{bmatrix} 1 \\ 3 \end{bmatrix}\\
\end{pmatrix}
is a span.<br>
Solution:
1. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 2 \\ -1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ 3 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \end{bmatrix} \\
\end{equation}
2. Transform the linear equation into its reduved echelon form:
$
\begin{pmatrix}
    2 & 1 &\bigm| & a \\
    -1 & 3 &\bigm| & b \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{2}}
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    2 & 1 &\bigm| & a \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    2 & 1 &\bigm| & a \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} 2+ \text{R}_{1}}
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 7 &\bigm| & a+2b \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 7 &\bigm| & a+2b \\
\end{pmatrix}
\xrightarrow{\frac{1}{7} \text{R}_{2}}
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1}-3 \text{R}_{2}}
\begin{pmatrix}
    -1 & 0 &\bigm| & \frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 0 &\bigm| & \frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
\xrightarrow{(-1)\text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & -\frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
- The final reduced row echelon is of the form:
$
\begin{pmatrix}
    -1 & 0 &\bigm| & \frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
\xrightarrow{(-1)\text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & -\frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
$\therefore$ it is a span

# Linear Combination of Vectors
---
- Let $v_1, v_2, ..., v_3$ be vectors $\in \mathbb{R}^n$.
- These vectors are linear combination of each other if there exists a coefficient to transform this vectors into a linear equation.

#### Example
Check if vector $v$ is a linear combination of the other given vectors.
 \begin{pmatrix}
    \textbf{v} = \begin{bmatrix} 2 \\ -2 \\ -1 \end{bmatrix}  \ 
    \textbf{u}_1 = \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix} \
    \textbf{u}_2 = \begin{bmatrix} 2 \\ -3 \\ 1 \end{bmatrix} \
    \textbf{u}_2 = \begin{bmatrix} 5 \\ 4 \\ 0 \end{bmatrix}\\
\end{pmatrix}
<br>
solution:<br>
a. The linear equation should be of the form $u_1+u_2+u_3=v$. <br><br>

b. Transform it into a linear equation:<br><br>
 $
    \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}x + \begin{bmatrix} 2 \\ -3 \\ 1 \end{bmatrix} y + \begin{bmatrix} 5 \\ -4 \\ 0 \end{bmatrix} z = \begin{bmatrix} 2 \\ -2 \\ -1 \end{bmatrix}
$<br><br>
c. We want to solve the system of linear equations:<br><br>
\begin{equation}
x+2y+5z=2 \\
-3y-4z=-2 \\
-x+y=-1
\end{equation}<br><br>
d. Transform the system of linear equations to an augmented matrix:<br>
<br><br>
$
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & -3 & -4 &\bigm| & -2 \\
    -1 &1 & 0 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    -1 & 1 & 0 &\bigm| & -1 \\
    0 & -3 & -4 &\bigm| & -2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    -1 & 1 & 0 &\bigm| & -1 \\
    0 & -3 & -4 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 3 & 5 &\bigm| & 1 \\
    0 & -3 & -4 &\bigm| & -2 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 3 & 5 &\bigm| & 1 \\
    0 & -3 & -4 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 3 & 5 &\bigm| & 1 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 3 & 5 &\bigm| & 1 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 5\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 3 & 0 &\bigm| & 6 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 3 & 0 &\bigm| & 6 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 1 & 0 &\bigm| & 2 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & 5 &\bigm| & 2 \\
    0 & 1 & 0 &\bigm| & 2 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & 7 \\
    0 & 1 & 0 &\bigm| & 2 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & 7 \\
    0 & 1 & 0 &\bigm| & 2 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 3 \\
    0 & 1 & 0 &\bigm| & 2 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{pmatrix}
$<br><br>
e. We can say that $x = 3$, $y=2$ and $z=-1$, and the linear combination is:<br><br>
\begin{equation}
\textbf{x}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}
+
\textbf{y}\begin{bmatrix} 2 \\ -3 \\ 1 \end{bmatrix}
+
\textbf{z}\begin{bmatrix} 5 \\ -4 \\ 0 \end{bmatrix}
= 
\begin{bmatrix} 2 \\ -2 \\ -1 \end{bmatrix}
\end{equation}
<br><br>
f. Plugging the values of $x = 3$, $y=2$ and $z=-1$, into the linear combination:
<br><br>
\begin{equation}
\textbf{3}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}
+
\textbf{2}\begin{bmatrix} 2 \\ -3 \\ 1 \end{bmatrix}
+
\textbf{-1}\begin{bmatrix} 5 \\ -4 \\ 0 \end{bmatrix}
= 
\begin{bmatrix} 2 \\ -2 \\ -1 \end{bmatrix}
\end{equation}<br><br>
g. Performing scalar multiplication on the vectors followed by the vector operation will yield that both sides of the equation are equal. 
<br><br>
$\therefore$ the vectors are linear combination of each other.
<br>


# Linear Dependence
---
- Given the vectors $\textbf{u}$,$\textbf{v}$ and $\textbf{w}$, and an equation $3\textbf{u}+2 \textbf{v} = \textbf{w}$. 
- Transforming the given equation to $3\textbf{u}+2\textbf{v}-\textbf{w} = 0$, we can say that $\textbf{w}$ is linearly depdent on $\textbf{u}$ and $\textbf{v}$.
## To check for linear dependence the following conditions must exist:
---
1. A set of vectors $\{\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n\}$ is linearly dependent if there are scalars $k_1,k_2,...,k_n$ at least one of which is not zero that will satisfy the linear equation:
$k_1x_1+k_2x_2+...+k_nx_n=0$.<br>
<strong><font color=red>$\to$</font></strong> If all the scalars, $k_1,k_2,...,k_n$ are zero then the vectors are linearly independent.
<br><br>
2. A set of vectors $\{\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n\} \in \mathbb{R}^n$ are linearly dependent $\iff$ at least one of the vectors can be expressed as a linear combination of the others.<br>
    - Because based on condition 1: $k_1x_1+k_2x_2+...+k_nx_n=0$
    - Then we can rewrite as <br> $k_2x_2+...+k_nx_n=k_1x_1$
    <br>or<br>
    $k_1x_1+...+k_nx_n=k_2x_2$
<br><br>
3. Let $\{\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n\} \in \mathbb{R}^n$ be <font color=purple>**row**</font> vectors. Let $\textbf{A}$ have a dimension of $m$ rows x $n$ columns:
\begin{equation}
\textbf{A} = 
\begin{bmatrix}
\textbf{v}_1 \\
\textbf{v}_2 \\
. \\
. \\
. \\
. \\
\textbf{v}_n \\
\end{bmatrix}
\end{equation}
Then, $\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n$ are linearly dependent $\iff rank(A)<m$.
<br><br>
4. Let $\{\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n\} \in \mathbb{R}^n$ be <font color=purple>**column**</font> vectors. Let $\textbf{A}$ have a dimension of $n$ rows $x$ $m$ columns:
\begin{equation}
\textbf{A} = 
\begin{bmatrix}
\textbf{v}_1 \\
\textbf{v}_2 \\
. \\
. \\
. \\
. \\
\textbf{v}_n \\
\end{bmatrix}
\end{equation}
Then, $\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n$ are linearly dependent if the dimension of matrix $A$ is $n$ rows and $m$ columns, and $m>n$.

##### Example
- Show that the given the vectors are linearly dependent:
\begin{pmatrix}
    \begin{bmatrix} 1 \\ 3 \end{bmatrix} \
    \begin{bmatrix} 2 \\ 4 \end{bmatrix} \
    \begin{bmatrix} 3 \\ 1 \end{bmatrix}\\
\end{pmatrix}
Solution:
- The number of columns $m=3$, the number of rows $n=2$, we can say: $3>2$, by condition 4, then we can say that the vectors are linearly dependent.

# Example Exercises
- Which of the two following is a linear equation:<br>
a. $x-\pi y+\sqrt{5}z=0$<br>
b. $x^2+y^2+z^2=1$<br>
c. $x-y+\sqrt{5z}=0$<br>
<br>
solution:
a. $x-\pi y+\sqrt{5}z=0$ is of the form $a_1x_1+a_2x_2+a_3x_3 = b$ so it is a linear equation.<br>
b. $x^2+y^2+z^2=1$ does not follow the form $a_1x_1+a_2x_2+a_3x_3 = b$ so it is not a linear equation.<br>
c. $x-y+\sqrt{5z}=0$ does not follow the form $a_1x_1+a_2x_2+a_3x_3 = b$ so it is not a linear equation.
<br>
<font color=green>----------------------------------------------------------------------------------------------------------</font>
<br><br>
- Find the solution of the linear equation $2x+2y+3z=4$.
Solution:<br>
a. We need to transform the linear equation into an augmented matrix, so<br> 
let: $y = s$ <br> $z = t$<br> the new equation becomes: $x+2s+3t = 4$.<br>
b. Solving for $x$ yields $x = 4-2s-3t$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 4-2s-3t \\
    0 & 1 & 0 &\bigm| & s \\
    0 & 0 & 1 &\bigm| & t \\
\end{pmatrix}<br>
d. We can have any arbitrary values of $s$ and $t$ that will satisfy $4-2s-3t$, these arbitrary values are the solutions to $y,z$. While the result from the formula $4-2s-3t$ is the solution to $x$.
<br>
<font color=green>----------------------------------------------------------------------------------------------------------</font>
<br><br>
- State whether the following matrix is in row echelon, reduced row echelon, or neither.<br>
a. \begin{pmatrix}
    1 & 0 & 1  \\
    0 & 0 & 3  \\
    0 & 1 & 0  \\
\end{pmatrix}<br>
b. \begin{pmatrix}
    7 & 0 & 1 & 0  \\
    0 & 1 & -1 & 4  \\
    0 & 0 & 0 & 0  \\
\end{pmatrix}<br>
c. \begin{pmatrix}
    0 & 1 & 3 & 0  \\
    0 & 0 & 0 & 1  \\
\end{pmatrix}<br>
solution:<br>
a. Is not in the row echelon form because the leading entry in row 2 appears to the right of row 3.<br>
b. This matrix is in row echelon form because majority of the row with zeroes are located at the lowest row, but this is not a reduced echelon since the leading entry of the first row is not 1.<br>
c. This is a reduced echelon form since majority of the row with zeroes are at the lowest row, and the leading entry of each row is 1.
<br>
<font color=green>----------------------------------------------------------------------------------------------------------</font>
<br><br>
- Determine the solution of the following systems of linear equations
$
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2+x_3 =0 \\
4x_1-x_2-+x_3 = 4 \\
\end{equation}
$
Solution:
<br>
a. Create an augmented matrix.<br>
b. Perform row operations.<br>
c. The result should either be in row echelon or reduced row echelon form.
<br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & 1 &\bigm| & 0 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow[\text{R}_{2} - 4\text{R}_{1}]{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 7 &\bigm| & -18 \\
    0 & -9 & -13 &\bigm| & -32 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 7 &\bigm| & -18 \\
    0 & -9 & -13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 9\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & \frac{-7}{5} &\bigm| & \frac{18}{5} \\
    0 & 0 & \frac{2}{5} &\bigm| & \frac{2}{5} \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & \frac{-7}{5} &\bigm| & \frac{18}{5} \\
    0 & 0 & \frac{2}{5} &\bigm| & \frac{2}{5} \\
\end{pmatrix}
\xrightarrow{\frac{5}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & \frac{-7}{5} &\bigm| & \frac{18}{5} \\
    0 & 0 & 1 &\bigm| & 1 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & \frac{-7}{5} &\bigm| & \frac{18}{5} \\
    0 & 0 & 1 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow[\text{R}_{1} + \frac{7}{5}\text{R}_{3}]{\text{R}_{1} + 3\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & 12 \\
    0 & 1 & 0 &\bigm| & 5 \\
    0 & 0 & 1 &\bigm| & 1 \\
\end{pmatrix}
$<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & 12 \\
    0 & 1 & 0 &\bigm| & 5 \\
    0 & 0 & 1 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 2 \\
    0 & 1 & 0 &\bigm| & 5 \\
    0 & 0 & 1 &\bigm| & 1 \\
\end{pmatrix}
$<br><br>
<br>
<font color=green>----------------------------------------------------------------------------------------------------------</font>
<br><br>
 - Determine if the vectors are linear combinations.
 \begin{pmatrix}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_1 = \begin{bmatrix} 1 \\ -1 \end{bmatrix}\
    \textbf{u}_2 = \begin{bmatrix} 2 \\ -1 \end{bmatrix}\\
\end{pmatrix}
<br>
solution:<br>
a. The linear equation should be of the form $u_1+u_2=v$, and transform it into a linear equation:<br>
 $
    \begin{bmatrix} 1 \\ -1 \end{bmatrix}x + \begin{bmatrix} 2 \\ -1 \end{bmatrix} y = \begin{bmatrix} 1 \\ 2 \end{bmatrix} 
$<br>
b. We want to solve the system of linear equations:<br>
\begin{equation}
x+2y=1 \\
-x-y=2
\end{equation}<br>
c. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    1 & 2 &\bigm| & 1 \\
    -1 & -1 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 &\bigm| & 1 \\
    0 & -1 &\bigm| & 3 \\
\end{pmatrix}
$
<br>
$
\begin{pmatrix}
    1 & 2 &\bigm| & 1 \\
    0 & -1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & -5 \\
    0 & -1 &\bigm| & 3 \\
\end{pmatrix}
$<br>
d. We can say that $x = -5$ and $y=3$, and the linear combination is $-5u_1+3u_2=v$.<br>
e. $\therefore$ The vectors are linear combination of each other.
<br>
<font color=green>----------------------------------------------------------------------------------------------------------</font>
<br><br>
- Determine of the given vector $b$ is a span of the matrix $A$.<br>
\begin{equation}
\textbf{A} = \begin{pmatrix}
    1 & 2 \\
    3 & 4 \\
\end{pmatrix}
,
\textbf{b} = \begin{pmatrix}
    5 \\
    6 \\
\end{pmatrix}
\end{equation}
<br>
Solution:<br>
a. The vector $b$ can only be a span of matrix $A$, $\iff$ the system of linear equation $\textbf{A}\textbf{x}=b$ has a solution, where $x = [x,y]^T$.<br>
b. Transforming $\textbf{A}\textbf{x}=b$<br>
\begin{equation}
\begin{pmatrix}
    1 & 2 \\
    3 & 4 \\
\end{pmatrix}
\begin{pmatrix}
    x \\
    y \\
\end{pmatrix} = \begin{pmatrix}
    5 \\
    6 \\
\end{pmatrix}
\end{equation}<br>
c. So the systems of linear equation is:<br>
\begin{equation}
x+2y=5 \\
3x+4y =6 \\
\end{equation}<br>
d. Transforming the system of linear equation to an augmented matrix, and finding the reduced echelon form:<br>
$
\begin{pmatrix}
    1 & 2 &\bigm| & 5 \\
    3 & 4 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 3\text{R}_{1}}
\begin{pmatrix}
    1 & 2 &\bigm| & 5 \\
    0 & -2 &\bigm| & -9 \\
\end{pmatrix}
$<br>
$
\begin{pmatrix}
    1 & 2 &\bigm| & 5 \\
    0 & -2 &\bigm| & -9 \\
\end{pmatrix}
\xrightarrow{\frac{-1}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 &\bigm| & 5 \\
    0 & 1 &\bigm| & \frac{9}{2} \\
\end{pmatrix}
$<br>
$
\begin{pmatrix}
    1 & 2 &\bigm| & 5 \\
    0 & 1 &\bigm| & \frac{9}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & -4 \\
    0 & 1 &\bigm| & \frac{9}{2} \\
\end{pmatrix}
$<br>
e. The solution for $\textbf{A}\textbf{x}=\textbf{b}$ is:
$
\textbf{A}
\begin{pmatrix}
    -4 \\
    \frac{9}{2} \\
\end{pmatrix}
=
\begin{pmatrix}
    5 \\
    6 \\
\end{pmatrix}
$<br>
f. Yes, the vector is a span of the matrix.<br>
<font color=green>----------------------------------------------------------------------------------------------------------</font>
<br><br>
- Show that the following vectors are linearly independent:
\begin{equation}
\begin{bmatrix}
    3 \\ 1 \\ 4 \\
\end{bmatrix}
,
\begin{bmatrix}
    -2 \\ 1 \\ -1 \\
\end{bmatrix}
\end{equation}
<br>
Solution:<br>
a. By definition:<br>
Let $\{\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n\} \in \mathbb{R}^n$ be <font color=purple>**column**</font> vectors. Let $\textbf{A}$ be a $mxn$ matrix:
\begin{bmatrix}
\textbf{v}_1 \\
\textbf{v}_2 \\
. \\
. \\
. \\
. \\
\textbf{v}_n \\
\end{bmatrix}
Then, $\textbf{v}_1,\textbf{v}_2,...,\textbf{v}_n$ are linearly dependent if the dimension of matrix $A$ is $n$ rows and $m$ columns, and $m>n$.<br>
b. Since the number of columns $m=2$, and the number of rows $n=3$ the condition $m>n$ is not satisfied, hence this is linearly independent.

# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---
1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$
- $cos{x}4y+z = \sqrt{3}$
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
- $x^1+y^1+z^1=0$
---
2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$
- $4x_1+3x_2+2x_3=1$
- $3x-6y=0$
---
3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 \\
2x+y = 3
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
\end{equation}
c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{equation}
<br>
---
4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>
---
5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}
c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>
d. <br>
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
<br>
---
6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br><br>
b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>
c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>
---
7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
---
8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}
b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
<br>
c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}