# Matrices
---

- A matrix is a rectangular array of scalars following the form:
\begin{align}
    \textbf{A} = \begin{bmatrix}
           a_{11} \ a_{12}  \ a_{13} \ ... \ a_{1j}\\
           a_{21} \ a_{22}  \ a_{23} \ ... \ a_{2j} \\
           a_{31} \ a_{32}  \ a_{33} \ ... \ a_{3j} \\
           . \ .  \ . \ ... \ . \\
           . \ .  \ . \ ... \ . \\
           . \ .  \ . \ ... \ . \\
           a_{i1} \ a_{i2}  \ a_{i3} \ ... \ a_{ij} \\
         \end{bmatrix}
  \end{align}<br>
- The size of a matrix is denoted by "x$x$n" (read as "m" by "n"), which is a matrix with m rows and n columns.
- the scalar entry of the matrix A can be denoted by $[a_{ij}]$. <br>
- The rows of the matrix are the i horizontal vectors of scalars:<br>
\begin{equation}
[a_{11} \ a_{12}  \ a_{13} \ ... \ a_{1j}], [a_{21} \ a_{22}  \ a_{23} \ ... \ a_{2j}], ...., [a_{i1} \ a_{i2}  \ a_{i3} \ ... \ a_{ij}]
\end{equation}<br>.
- The columns of A are the j vertical vectors:<br>
\begin{align}\begin{bmatrix}
           a_{11}\\ a_{21}  \\ a_{31} \\ ... \\ a_{i1}\\
         \end{bmatrix}
         \begin{bmatrix}
           a_{12}\\ a_{22}  \\ a_{32} \\ ... \\ a_{i2}\\
         \end{bmatrix}
         \begin{bmatrix}
           a_{13}\\ a_{23}  \\ a_{33} \\ ... \\ a_{i3}\\
         \end{bmatrix}
         \begin{bmatrix}
           .\\ .  \\ . \\ ... \\ .\\
         \end{bmatrix}
         \begin{bmatrix}
           .\\ .  \\ . \\ ... \\ .\\
         \end{bmatrix}
         \begin{bmatrix}
           a_{1j}\\ a_{2j}  \\ a_{3j} \\ ... \\ a_{ij}\\
         \end{bmatrix}
  \end{align}<br><br>
- Two matrices are equal if both matrices have the same size, and their entried are the same.
  
## Example
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 \ -4  \ 5 \\
           0 \ 3  \ -2 \\
         \end{bmatrix}
  \end{align}<br>
- Matrix $\textbf{A}$ is a 2 x 3 matrix (read as 2 by 3 matrix) with 2 rows and 3 columns.<br>
- The row vector of the matrix is:<br>
\begin{equation}
[1 \ -4 \ 5], [0 \ 3 \ -2]
\end{equation}<br>.
- The column vector of the matrix is:<br>
\begin{align}\begin{bmatrix}
           1\\ 0\\
         \end{bmatrix}
         \begin{bmatrix}
           -4\\ 3  \\
         \end{bmatrix}
         \begin{bmatrix}
           5\\ -2  \\
         \end{bmatrix}
  \end{align}<br><br>

# Matrix Addition and Scalar Multiplication
---

- If the entry of matrix $\textbf{A} = [a_{ij}]$ and the entry of matrix $\textbf{b} = [b_{ij}]$.
- To perform matrix addition the **rule** is that both matrices should be of th **same** dimension.
- Matrix addition is defined as $\textbf{A}+\textbf{B}$.:
\begin{align}
    \textbf{A+B} = \begin{bmatrix}
           (a_{11}+b_{11}) \ \ \ (a_{12}+b_{12}) \ \  \ (a_{13}+b_{13})\ \ \ ... \ \ \ (a_{1j}+b_{1j})\\
           (a_{21}+b_{21}) \ \ \ (a_{22}+b_{22}) \ \  \ (a_{23}+b_{23})\ \ \ ... \ \ \ (a_{2j}+b_{2j})\\
           (a_{31}+b_{31}) \ \ \ (a_{32}+b_{32}) \ \  \ (a_{33}+b_{33})\ \ \ ... \ \ \ (a_{3j}+b_{3j})\\
           . \ .  \ . \ ... \ . \\
           . \ .  \ . \ ... \ . \\
           . \ .  \ . \ ... \ . \\
           (a_{i1}+b_{i1}) \ \ \ (a_{i2}+b_{i2}) \ \  \ (a_{i3}+b_{i3})\ \ \ ... \ \ \ (a_{ij}+b_{ij})\\
         \end{bmatrix}
  \end{align}<br>
- The scalar multiplication between a scalar, $textbf{k}$ and a matrix $\textbf{A}$ is:<br>
\begin{align}
    k\textbf{A} = \begin{bmatrix}
           ka_{11} \ ka_{12}  \ ka_{13} \ ... \ ka_{1j}\\
           ka_{21} \ ka_{22}  \ ka_{23} \ ... \ ka_{2j} \\
           ka_{31} \ ka_{32}  \ ka_{33} \ ... \ ka_{3j} \\
           . \ .  \ . \ ... \ . \\
           . \ .  \ . \ ... \ . \\
           . \ .  \ . \ ... \ . \\
           ka_{i1} \ ka_{i2}  \ ka_{i3} \ ... \ ka_{ij} \\
         \end{bmatrix}
  \end{align}<br>
<br>
## Theorems
---
- $A-B = A + -1(B)$
- $(A+B)+C= A+(B+C)$
- $A+0= 0+A =A$
- $A+B=B+A$
- $(k+k')A = kA + k'A$
- $(kk')A = k(k'A)$
 
#### Example 1:
- Let Matrix A be:<br>
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 \ \ \ \ \ 3  \\
           2 \ \ \ -1  \\
         \end{bmatrix}
  \end{align}<br>
- The dimension of matrix $A$ is (2 x 2), 2 rows and 2 columns.<br><br><br>
- Let Matrix B be:<br>
\begin{align}
    \textbf{B} = \begin{bmatrix}
           2 \ \ \ \  0 \\
           5 \ \ \ -2  \\
         \end{bmatrix}
  \end{align}<br><br>
  \begin{align}
    \textbf{B} = \begin{bmatrix}
           1+2 \ \ \ \  3+0 \\
           2+5 \ \ \ -1-2  \\
         \end{bmatrix}
  \end{align}<br><br>
    \begin{align}
    \textbf{B} = \begin{bmatrix}
           3 \ \ \ \  3 \\
           7 \ \ \ -3  \\
         \end{bmatrix}
  \end{align}<br><br>

In [3]:
#Pythonic Solution
import numpy as np
A = np.array([[1,3],[2,-1]])
B = np.array([[2,0],[5,-2]])
A+B

array([[ 3,  3],
       [ 7, -3]])

# Matrix Multiplication
---
- Given two matrices A and B.
- Let Matrix A be:<br>
\begin{align}
    \textbf{A} = \begin{bmatrix}
           a_{11} \ a_{12}  \\
           a_{21} \ a_{22}  \\
         \end{bmatrix}
  \end{align}<br>
  
- Let Matrix B be:<br>
\begin{align}
    \textbf{B} = \begin{bmatrix}
           b_{11} \ b_{12}  \\
           b_{21} \ b_{22}  \\
         \end{bmatrix}
  \end{align}<br>
- The matrix multiplication is:
\begin{align}
    \textbf{A}\textbf{B} = \begin{bmatrix}
           \begin{bmatrix} a_{11} \ a_{12}  \end{bmatrix} \begin{bmatrix} b_{11} \\ b_{21}  \end{bmatrix} \ \ \ \begin{bmatrix} a_{11} \ a_{12}  \end{bmatrix} \begin{bmatrix} b_{12} \\ b_{22}  \end{bmatrix} \\
          \begin{bmatrix} a_{21} \ a_{22}  \end{bmatrix} \begin{bmatrix} b_{11} \\ b_{21}  \end{bmatrix} \ \ \ \begin{bmatrix} a_{21} \ a_{22}  \end{bmatrix} \begin{bmatrix} b_{12} \\ b_{22}  \end{bmatrix} \\
         \end{bmatrix}\\
  \end{align}<br>
\begin{align}
    \textbf{AB} = \begin{bmatrix}
           (a_{11}b_{11})+(a_{12}b_{21}) \ \ \ \  (a_{11}b_{12})+(a_{12}b_{22}) \\
           (a_{21}b_{11})+(a_{22}b_{21}) \ \ \ \  (a_{21}b_{22})+(a_{12}b_{22}) \\
         \end{bmatrix}
  \end{align}<br>
- To perform the matrix multiplication the following condition must follow:<br>
             - If matrix $A$ has a $(nxm)$ dimension, matrix $B$ must have $(mxp)$ dimension. The product of the matrix multiplication $AxB$ has a dimension of $nxp$.<br><br><br>
             
## Theorems on Matrix Multiplication:
---
- Let $A, B$ and $C$ be matrices, then:
1. $(AB)C = A(BC) \to Associativity$.
2. $A(B+C) = (AB)+(AC) \to Left \ Distributive$.
3. $(B+C)A = (BA)+(CA) \to Right \ Distributive$.
4. $k(AB) = (kA)B=A(kB) \to Right \ Scalar Multiplication$.
         
### Example 1:
- Let Matrix A be:<br>
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 \ \ \ \ \ 3  \\
           2 \ \ \ -1  \\
         \end{bmatrix}
  \end{align}<br>
- The dimension of matrix $A$ is (2 x 2), 2 rows and 2 columns.<br><br><br>
- Let Matrix B be:<br>
\begin{align}
    \textbf{B} = \begin{bmatrix}
           2 \ \ \ \  0 \ \ \ -4  \\
           5 \ \ \ -2 \ \ \ 6 \\
         \end{bmatrix}
  \end{align}<br>
- Matrix $B$ has a (2 x 3) dimension.<br>
- Since $A$ is (2x2) and $B$ is (2x3) then it satisfies the (nxm)x(mxp) = (nxp) condition.
- The matrix multiplication is:
\begin{align}
    \textbf{A}\textbf{B} = \begin{bmatrix}
           \begin{bmatrix} 1 \ \  3  \end{bmatrix} \begin{bmatrix} 2 \\ 5  \end{bmatrix} \ \ \ \begin{bmatrix} 1 \ \ 3  \end{bmatrix} \begin{bmatrix} 0 \\ -2  \end{bmatrix} \ \ \ \begin{bmatrix} 1 \ \ 3  \end{bmatrix} \begin{bmatrix} -4 \\ 6  \end{bmatrix} \\ \\
          \begin{bmatrix} 2 \ \ \ -1  \end{bmatrix} \begin{bmatrix} 2 \\ 5  \end{bmatrix} \ \ \ \begin{bmatrix} 2 \ \ \ -1  \end{bmatrix} \begin{bmatrix} 0 \\ -2  \end{bmatrix} \begin{bmatrix} 2 \\ 5  \end{bmatrix} \ \ \ \begin{bmatrix} 2 \ \ \ -1  \end{bmatrix} \begin{bmatrix} -4 \\ 6  \end{bmatrix} \\
         \end{bmatrix}\\
  \end{align}
<br>
<br>
\begin{align}
    \textbf{AB} = \begin{bmatrix}
           (1)(2)+(3)(5) \ \ \ \  (1)(0)+(3)(-2)  \ \ \ \  (1)(-4)+(3)(6)\\
           (2)(2)+(-1)(5) \ \ \ \  (2)(0)+(-1)(-2)  \ \ \ \  (2)(-4)+(-1)(6) \\
         \end{bmatrix}
  \end{align}
<br>
<br>
\begin{align}
    \textbf{AB} = \begin{bmatrix}
           2+15 \ \ \ \  0-6  \ \ \ \  -4+18\\
           4-5 \ \ \ \  0+2  \ \ \ \  -8-6 \\
         \end{bmatrix}
  \end{align}
<br>
<br>
\begin{align}
    \textbf{AB} = \begin{bmatrix}
           17 \ \ \ \  -6  \ \ \ \  14\\
           -1 \ \ \ \  2  \ \ \ \  -14 \\
         \end{bmatrix}
  \end{align}
  
  ### Example 2:
- Let Matrix A be:<br>
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 \ \ \ 2\\
           3 \ \ \ 4\\
         \end{bmatrix}
  \end{align}<br>

- Let Matrix B be:<br>
\begin{align}
    \textbf{B} = \begin{bmatrix}
           5 \ \ \ 6  \\
           0 \ \ \ -2  \\
         \end{bmatrix}
  \end{align}<br>
<br>
#### 1. Show that:
<br>
\begin{align}
    \textbf{AB} = \begin{bmatrix}
           5 \ \ \ \  2  \\
           15 \ \ \ \ 10  \\
         \end{bmatrix}
  \end{align}
  
#### 2. Show that:
<br>
\begin{align}
    \textbf{BA} = \begin{bmatrix}
           23 \ \ \ \  34  \\
           -6 \ \ \ \ -8  \\
         \end{bmatrix}
  \end{align}

In [12]:
# Pythonic Solution
A = np.array([[1,3],[2,-1]])
B = np.array([[2,0,-4],[5,-2,6]])
np.matmul(A,B)

array([[ 17,  -6,  14],
       [ -1,   2, -14]])

In [14]:
# Pythonic Solution
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[0,-2]])
np.matmul(A,B)

array([[ 5,  2],
       [15, 10]])

In [15]:
# Pythonic Solution
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[0,-2]])
np.matmul(B,A)

array([[23, 34],
       [-6, -8]])

# Partitioned Matrices
---
- A partitioned matrix occurs when when a matrix is subdivided into sub-matrices.
- A matrix can be converted into a partitioned matrix  by introducing vertical and horizontal lines, creating blocks of smaller matrices.
#### Example
- Given a $4x4$ matrix (4 rows by 4 columns).
\begin{equation}
C = \begin{bmatrix}
1 & 0 & 0 & 2 & 1 \\
0 & 1 & 0 & 1 & 2 \\
0 & 0 & 1 & 4 & 3 \\
0 & 0 & 0 & 1 & 4 \\
0 & 0 & 0 & 1 & 4 \\
\end{bmatrix}
\end{equation}
<br><br>
- Can be partitioned into a sub-matrices that are $2x2$ by size.
\begin{equation}
C=\begin{array}{ccc|cc}
1 & 0 & 0 & 2 & 1 \\
0 & 1 & 0 & 1 & 2 \\
0 & 0 & 1 & 4 & 3 \\
\hline
0 & 0 & 0 & 1 & 4 \\
0 & 0 & 0 & 1 & 4 \\
\end{array}
\end{equation}
<br><br>
- We can denote each sub-matrix as $M,N,R,S$.
\begin{equation}
C=\begin{array}{c|c}
M & N \\
\hline
R & S
\end{array}
\end{equation}
<br><br>
- Where M is a $3x3$ Identity matrix.
\begin{equation}
M = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\end{equation}
<br><br>
- N is a $3x2$ matrix.
\begin{equation}
N = \begin{bmatrix}
2 & 1 \\
1 & 2 \\
4 & 3 \\
\end{bmatrix}
\end{equation}
<br><br>
- N is a $2x3$ zero matrix.
\begin{equation}
R = \begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{bmatrix}
\end{equation}
<br><br>
- N is a $2x2$ matrix.
\begin{equation}
R = \begin{bmatrix}
1 & 4 \\
1 & 4 \\
\end{bmatrix}
\end{equation}
<br><br>

#### Hint:


# Transpose of a Matrix
---
- Let a matrix be doenated as $A$, the transpose of this matrix is denoted as $A^T$.
- If a given matrix has a dimension of $mxn$, and an entry of $A = [a_{ij}]$, the tranpose of this matrix will have a dimension of $nxm$, and an entry of $A^T = [a_{ji}]$.
## Theorems on Matrix Tranpose
---
1. $(A+B)^T = A^T+B^T$
2. $(A^T)^T = A$
3. $(kA)^T = kA^T$
4. $(AB)^T = B^TA^T \to$ **<font color=blue>observe that the positioning is reversed!<font>**
### Example:
- Let Matrix $C$ be:<br>
\begin{align}
    \textbf{C} = \begin{bmatrix}
           1 \ \ \ \  2 \ \ \ 3  \\
           4 \ \ \ 5 \ \ \ 6 \\
         \end{bmatrix}
  \end{align}<br> 
\begin{align}
    \textbf{C}^T = \begin{bmatrix}
           1 \ \ \ \  4 \\
           2 \ \ \ \  5 \\
           3 \ \ \ \  6 \\
         \end{bmatrix}
  \end{align}<br> 

In [16]:
# Pythonic Solution
# Pythonic Solution
C = np.array([[1,2,3],[4,5,6]])
C.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Square Matrix
---
- A square matrix is any matrix with the same number of rows and columns.
- The dimension of a square matrix is $nxn$.
### Examples of Square Matrix:
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 \ \ \ \  4 \\
           2 \ \ \ \  5 \\
         \end{bmatrix}
  \end{align}<br> 
\begin{align}
    \textbf{B} = \begin{bmatrix}
           1 \ \ \ \  2 \ \ \ \ 3 \\
           6 \ \ \ \  5 \ \ \ \ 4 \\
           7 \ \ \ \  9 \ \ \ \ 8 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{C} = \begin{bmatrix}
           1 \ \ \ \  5 \ \ \ \ 8 \ \ \ \ 10 \\
           11 \ \ \ \  2 \ \ \ \ 6 \ \ \ \ 9 \\
           14 \ \ \ \  12 \ \ \ \ 3 \ \ \ \ 7 \\
           16 \ \ \ \  15 \ \ \ \ 13 \ \ \ \ 4 \\
         \end{bmatrix}
  \end{align}<br>
## Properties of a Square Matrix:
**Diagonal of a Matrix**
- If a given matrix is a square matrix, the diagonal of the square matrix are diagonal the elements$= [a_{11},a_{22},a_{33},...,a_{nn}]$.
#### Example of the diagonal of a matrix:
- Given the matrix $C$, defined as:
\begin{align}
    \textbf{C} = \begin{bmatrix}
           1 \ \ \ \  5 \ \ \ \ 8 \ \ \ \ 10 \\
           11 \ \ \ \  2 \ \ \ \ 6 \ \ \ \ 9 \\
           14 \ \ \ \  12 \ \ \ \ 3 \ \ \ \ 7 \\
           16 \ \ \ \  15 \ \ \ \ 13 \ \ \ \ 4 \\
         \end{bmatrix}
  \end{align}<br>
- The diagonal of this matrix is $[1,2,3,4]$
***Trace of a Matrix**
- Given a square matrix, $A$, the trace of the matrix, denoted as $tr(A)$ is the sum of its diagonals:<br>
\begin{equation}
tr(A) = a_{11} + a_{22} + ... + a_{nn}
\end{equation}
#### Example of the trace of a matrix:
- Given the matrix $C$, defined as:
\begin{align}
    \textbf{C} = \begin{bmatrix}
           1 \ \ \ \  5 \ \ \ \ 8 \ \ \ \ 10 \\
           11 \ \ \ \  2 \ \ \ \ 6 \ \ \ \ 9 \\
           14 \ \ \ \  12 \ \ \ \ 3 \ \ \ \ 7 \\
           16 \ \ \ \  15 \ \ \ \ 13 \ \ \ \ 4 \\
         \end{bmatrix}
  \end{align}<br>
- $tr(C) = 1+2+3+4 = 10$

## Theorems
- Given two square matrices, $A$ and $B$, and a scalar, $k$, then:
1. $tr(A+B) = tr(A)+tr(B)$
2. $tr(kA) = k \ tr(A)$
3. $tr(A^T) = tr(A)$
4. $tr(AB) = tr(BA)$

In [39]:
# Pythonic Solution
C = np.array([[1,5,8,10],[11,2,6,9],[14,12,3,7],[16,15,13,4]])
print("Diagonal: ", np.diag(C))
print("Trace: ", np.trace(C))

Diagonal:  [1 2 3 4]
Trace:  10


# Identity and Scalar Matrices
---
- Given a square matrix, if the values of the diagonal value of this square matrix are 1's and o elsewhere, this matrix is called an identity matrix, denoted as $I$ or $I_n$, where $n$ is the dimension of the square matrix.

#### Example:
\begin{align}
    \textbf{I}_2 = \begin{bmatrix}
           1 \ \ \ \  0 \\
           0 \ \ \ \  1 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{I}_{3} = \begin{bmatrix}
           1 \ \ \ \  0 \ \ \ \ 0\\
           0 \ \ \ \  1 \ \ \ \ 0 \\
           0 \ \ \ \  0 \ \ \ \ 1 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{I}_{4} = \begin{bmatrix}
           1 \ \ \ \  0 \ \ \ \ 0 \ \ \ \ 0 \\
           0 \ \ \ \ 1 \ \ \ \ 0 \ \ \ \ 0 \\
           0 \ \ \ \  0 \ \ \ \ 1 \ \ \ \ 0 \\
           0 \ \ \ \  0 \ \ \ \ 0 \ \ \ \ 1 \\
         \end{bmatrix}
  \end{align}<br>
## <font color=Purple> Some Notes </font>
- Given a square matrix, $A$, with the same dimension as the identity matrix $I$:
\begin{equation}
AI = IA = A
\end{equation}
- Given a non-square matrix, $B$, with a dimension (mxn), then:
\begin{equation}
AI_n = I_mA = A \to observe \ the \ dimention \ of \ the \ subscript.
\end{equation}
- For any scalar $k$, the matrix $kI_n$ which contains the scalar values at the diagonal, and zero elsewhere is called the scalar matrix.
#### Example:
\begin{align}
    \textbf{5I}_2 = \begin{bmatrix}
           5 \ \ \ \  0 \\
           0 \ \ \ \  5 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{4I}_{3} = \begin{bmatrix}
           4 \ \ \ \  0 \ \ \ \ 0\\
           0 \ \ \ \  4 \ \ \ \ 0 \\
           0 \ \ \ \  0 \ \ \ \ 4 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{7I}_{4} = \begin{bmatrix}
           7 \ \ \ \  0 \ \ \ \ 0 \ \ \ \ 0 \\
           0 \ \ \ \ 7 \ \ \ \ 0 \ \ \ \ 0 \\
           0 \ \ \ \  0 \ \ \ \ 7 \ \ \ \ 0 \\
           0 \ \ \ \  0 \ \ \ \ 0 \ \ \ \ 7 \\
         \end{bmatrix}
  \end{align}<br>
- **NOTE:** $(kI)A =k(IA)=kA$.

# Power of Matrices and Polynomial Function of Matrices
---
- Given a square matrix, $A$, the power of a square matrix is denoted by:
\begin{equation}
A^{n+1} = A^nA
\end{equation}
#### Example:
- Given a square matrix A, the following powers of A are expressed as:
1. $A^2 = AA$
2. $A^3 = A^2A$
3. $A^4 = A^3A $
<br>
- Given a function $f(x) = a_0+a_1x+a_2x^2+....+a_nx^n$, the polynomials of a matrix, is simply replacing the x's with the square matrix, $A$, such that: $f(x) = a_0I+a_1A+a_2A^2+....+a_nA^n$
#### Example:
- Given a square matrix:
\begin{align}
    \textbf{A} = \begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ -4 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{A}^2 = \begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ -4 \\
         \end{bmatrix}\begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ -4 \\ 
         \end{bmatrix}= \begin{bmatrix}
           7 \ \  -6 \\
           -9 \ \ \ \ 22 \\
         \end{bmatrix}
  \end{align}<br>
\begin{align}
    \textbf{A}^3 = \textbf{A}^2A  = \begin{bmatrix}
           7 \ \  -6 \\
           -9 \ \ \ \ 22 \\
         \end{bmatrix}\begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ -4 \\ 
         \end{bmatrix} = \begin{bmatrix}
           -11 \ \ \ \  38 \\
           57 \ -106 \\ 
         \end{bmatrix}
  \end{align}<br>
  
- given $f(x) = 2x^2-3x+5$, the polynomial of the matrix $A$, is:
\begin{equation}
f(A) = 2A^2-3A+5I
\end{equation}<br><br>
\begin{equation}
f(A) = 2\begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ \ \ \ -4 \\
         \end{bmatrix}^2-3\begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ \ \ \ -4 \\
         \end{bmatrix}+5\begin{bmatrix}
           1 \ \  0 \\
           0 \ \ \ \ 1 \\
         \end{bmatrix}
\end{equation}<br><br>
\begin{equation}
f(A) = 2\begin{bmatrix}
           7 \ \  -6 \\
           -9 \ \ \ \ 22 \\
         \end{bmatrix}-3\begin{bmatrix}
           1 \ \ \ \  2 \\
           3 \ \ \ \ -4 \\
         \end{bmatrix}+5\begin{bmatrix}
           1 \ \  0 \\
           0 \ \ \ \ 1 \\
         \end{bmatrix}
\end{equation}<br><br>
\begin{equation}
f(A) = \begin{bmatrix}
           16 \ \  -18 \\
           -27 \ \ \ \ 61 \\
         \end{bmatrix}
\end{equation}

In [51]:
# Pythonic Solution for powers of matrices
A = np.array([[1,2],[3,-4]])
print("A^2: ",np.matmul(A,A))
print("A^3: ",np.matmul(np.matmul(A,A),A))

A^2:  [[ 7 -6]
 [-9 22]]
A^3:  [[ -11   38]
 [  57 -106]]


# Invertible (Non-Singular) of 2x2 Matrices
---
- A 2x2 matrix $A$ is invertible, if there exist a matrix $A^{-1}$, such that:$AA^{-1}=A^{-1}A=I_n$<br>
- A 2x2 Matrix $A^{-1}$ is called the inverse of $A$.
- Note that if $A$ and $A^{-1}$ are inverses, then: $(AA^{-1})^{-1} = (A^{-1})^{-1}A^{-1}$.

#### Example 1
- Let Matrix A be:<br>
\begin{align}
    \textbf{A} = \begin{bmatrix}
           2 \ \ \ 5\\
           1 \ \ \ 3\\
         \end{bmatrix}
  \end{align}<br>

- Let Matrix B be:<br>
\begin{align}
    \textbf{B} = \begin{bmatrix}
           3 \ \ \ -5  \\
           -1 \ \ \ \ \ \ 2  \\
         \end{bmatrix}
  \end{align}<br>
<br>
\begin{align}
    \textbf{AB} = \begin{bmatrix}
           2 & 5  \\
           1 & 3  \\
         \end{bmatrix}
         \begin{bmatrix}
           3 & -5  \\
           -1 & 2  \\
         \end{bmatrix} = 
         \begin{bmatrix}
           (2)(3)+(5)(-1) & (2)(-5)+(5)(2)  \\
           (1)(3)+(3)(-1) & (1)(-5)+(3)(2)  \\
         \end{bmatrix} =
         \begin{bmatrix}
           1 & 0  \\
           0 & 1  \\
         \end{bmatrix} = I_2
  \end{align}<br>
  <br>
\begin{align}
    \textbf{BA} = \begin{bmatrix}
           3 & -5  \\
           -1 & 2  \\
         \end{bmatrix}
         \begin{bmatrix}
           2 & 5  \\
           1 & 3  \\
         \end{bmatrix} = 
         \begin{bmatrix}
           (3)(2)+(1)(-5) & (3)(5)+(-5)(3)  \\
           (-1)(2)+(2)(1) & (-1)(5)+(2)(3)  \\
         \end{bmatrix} =
         \begin{bmatrix}
           1 & 0  \\
           0 & 1  \\
         \end{bmatrix} = I_2
  \end{align}<br>
  
# Theorems on nxn Invertible Matrices (not necessarily 2x2)
---
- If a matrix, $A$, is invertible then its inverse is unique.
- If a matrix, $A$, is an invertible $nxn$ matrix, then the system of linear equations given by $A \textbf{x} = \textbf{b}$ has the unique solution $\textbf = A^{-1} \textbf{b}$.

# Finding the determinant of a 2x2 Matrix
---
- If $A$ is a 2x2 matrix:
\begin{equation}
\textbf{A}=
\begin{bmatrix}
           a & b  \\
           c & d  \\
         \end{bmatrix}
\end{equation}
- Then $A$ is invertible if $ad-bc \neq 0$, in which case:
\begin{equation}
\textbf{A}^{-1}=
\frac{1}{ad-bc}
\begin{bmatrix}
           d & -b  \\
           -c & a  \\
         \end{bmatrix}
\end{equation}
- ad-bc is called the **determinant** of the matrix $A$, and is denoted by $\textbf{det}(A)$
\begin{equation}
\textbf{A}^{-1}=
\frac{1}{\textbf{det}(A)}
\begin{bmatrix}
           d & -b  \\
           -c & a  \\
         \end{bmatrix}
\end{equation}
- <font color=red><b>NOTE</b></font>: When $ad-bc = 0$, then the matrix is not invertible.
    
#### Example
- Find the inverse of:
\begin{equation}
\textbf{A} =
\begin{bmatrix}
           1 & 2  \\
           3 & 4  \\
\end{bmatrix}
\end{equation}
- Solution:
\begin{equation}
\textbf{A}^{-1}=
\frac{1}{\textbf{det}(A)}
\begin{bmatrix}
           d & -b  \\
           -c & a  \\
         \end{bmatrix}
         =
         \frac{1}{ad-bc}
         \begin{bmatrix}
           d & -b  \\
           -c & a  \\
         \end{bmatrix} =
         \frac{1}{(1)(4)-(2)(3)}
         \begin{bmatrix}
           4 & -2  \\
           -3 & 1  \\
           \end{bmatrix} = 
         \frac{1}{-2}
         \begin{bmatrix}
           4 & -2  \\
           -3 & 1  \\
           \end{bmatrix} = 
         \begin{bmatrix}
           -2 & 1  \\
           \frac{3}{2} & \frac{-1}{2}  \\
           \end{bmatrix}
\end{equation}

# Properties of an Invertible Matrices
---
1. If A is an invertible matrix, then $A^{-1}$ is also an invertible matrix:
\begin{equation}
(A^{-1})^{-1} = A
\end{equation}
2.If A is an invertible matrix and c is a nonzero scalar matrix, if $cA$ is an invertible matrix then:
\begin{equation}
(cA)^{-1} = \frac{1}{c}A^{-1}
\end{equation}
3. If A and B are invertible matrices of the same size, and $AB$ is invertible, then:
\begin{equation}
(AB)^{-1} = B^{-1}A^{-1}
\end{equation}
4. If A is an invertible matrix and $A^T$ is invertible then:
\begin{equation}
(A^T)^{-1} = (A^{-1})^T
\end{equation}
5. If a is an iinvertible matrix, then $A^n$ is invertible for all non-negative integers, $n$:
\begin{equation}
(A^n)^{-1} = (A^{-1})^n
\end{equation}
#### Example
---
- The properties of invertible matrices is very useful in matrix manipulation, many modern data science techniques like non-negative matrix factorization, principal component analysis, and singular value decomposition are often derived by manipulating property of invertible matrices.
- For the matrix equation $A^{-1}(BX)^{-1} = (A^{-1}B^3)^2$, find $X$
- Solution:
\begin{equation}
A^{-1}(BX)^{-1} = (A^{-1}B^3)^2
\\
(A)A^{-1}(BX)^{-1} = (A^{-1}B^3)^2(A) \ \to \ Multiply \ both \ sides \ with \ A.
\\
I(BX)^{-1}= (A)(A^{-1}B^3)^2 \ \to \ AA^{-1} = I \ by \ definition \ of \ inverse \ of \ matrices.
\\
X^{-1}B^{-1} = A(A^{-1}B^3)^2 \ \to \ Note \ on \ property \ 3.
\\
X^{-1}B^{-1}(B) = A(A^{-1}B^3)^2(B) \ \to \ Multiply \ both \ sides \ with \ B.
\\
X^{-1}I = A(A^{-1}B^3)^2(B) \ \to \ BB^{-1} = I \ by \ definition \ of \ inverse \ of \ matrices.
\\
X^{-1} = A(A^{-1}B^3)^2(B)
\\
X^{-1}X = A(A^{-1}B^3)^2(B)(X) \ \to \ Multiply \ both \ sides \ with \ X.
\\
I = A(A^{-1}B^3)^2(B)(X)
\\
\end{equation}

- Solve for X
\begin{equation}
I (A^{-1})(((A^{-1}B^3)^2)^-1)(B^{-1})= (AA^{-1})(A^{-1}B^3)^2((A^{-1}B^3)^2)^{-1}(BB^{-1})X
\\
A^{-1}((A^{-1})^2)^{-1}((B^3)^2)^{-1}(B^-1)= X
\\
A^{-1}((A^{-1})^{-1})^2((B^3)^2)^{-1}(B^-1)= X
\\
A^{-1}(A)^2(B^6)^{-1}(B^-1)= X
\\
A^{-1}(A)(A)(B^{-6})(B^-1)= X
\\
I(A)(B^{-6})(B^-1)= X
\\
(A)(B^{-7})= X
\\
B^{-4}AB^{-3} = X
\end{equation}

# Gauss-Jordan Methods for Determining Inverses
---
- The goal here is to:
\begin{equation}
\begin{bmatrix}
A|I 
\end{bmatrix}
\to 
\begin{bmatrix}
I|A^{-1} 
\end{bmatrix}
\end{equation}
#### Example
- Find the inverse of:
\begin{equation}
A = \begin{bmatrix}
1 & 2 & -1 \\
2 & 2 & 4 \\
1 & 3 & -3 \\
\end{bmatrix}
\end{equation}
- Solution:
\begin{equation}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
2 & 2 & 4 & 0 & 1 & 0\\
1 & 3 & -3 & 0 & 0 & 1\\
\end{array}
\xrightarrow[\text{R}_{3}-\text{R}_{1}]{\text{R}_{2} - 2\text{R}_{1}}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
0 & -2 & 6 & -2 & 1 & 0\\
0 & 1 & -2 & -1 & 0 & 1\\
\end{array}
\end{equation}
<br><br>
\begin{equation}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
0 & -2 & 6 & -2 & 1 & 0\\
0 & 1 & -2 & -1 & 0 & 1\\
\end{array}
\xrightarrow{\frac{-1}{2}\text{R}_{2}}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
0 & 1 & -3 & 1 & \frac{-1}{2} & 0\\
0 & 1 & -2 & -1 & 0 & 1\\
\end{array}
\end{equation}
<br><br>
\begin{equation}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
0 & 1 & -3 & 1 & \frac{-1}{2} & 0\\
0 & 1 & -2 & -1 & 0 & 1\\
\end{array}
\xrightarrow{\text{R}_{3}-\text{R}_{2}}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
0 & 1 & -3 & 1 & \frac{-1}{2} & 0\\
0 & 0 & 1 & -2 & \frac{1}{2} & 1\\
\end{array}
\end{equation}
<br><br>
\begin{equation}
\begin{array}{ccc|ccc}
1 & 2 & -1 & 1 & 0 & 0 \\
0 & 1 & -3 & 1 & \frac{-1}{2} & 0\\
0 & 0 & 1 & -2 & \frac{1}{2} & 1\\
\end{array}
\xrightarrow[\text{R}_{1}+\text{R}_{3}]{\text{R}_{2} - 3\text{R}_{3}}
\begin{array}{ccc|ccc}
1 & 2 & 0 & -1 & \frac{1}{2} & 1 \\
0 & 1 & 0 & -5 & 1 & 3 \\
0 & 0 & 1 & -2 & \frac{1}{2} & 1\\
\end{array}
\end{equation}
<br><br>
\begin{equation}
\begin{array}{ccc|ccc}
1 & 2 & 0 & -1 & \frac{1}{2} & 1 \\
0 & 1 & 0 & -5 & 1 & 3 \\
0 & 0 & 1 & -2 & \frac{1}{2} & 1\\
\end{array}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{array}{ccc|ccc}
1 & 0 & 0 & 9 & \frac{-3}{2} & -5 \\
0 & 1 & 0 & -5 & 1 & 3 \\
0 & 0 & 1 & -2 & \frac{1}{2} & 1\\
\end{array}
\end{equation}
<br><br>
\begin{equation}
\therefore A^{-1} = \begin{bmatrix}
9 & \frac{-3}{2} & -5 \\
-5 & 1 & 3 \\
-2 & \frac{1}{2} & 1 \\
\end{bmatrix}
\end{equation}

In [5]:
# Pythonic Solution for inverse of matrices.
import numpy as np
A = np.array([[2,5],[1,3]])
inverse_A = np.linalg.inv(A)
print(inverse_A)
print('---------------------')
print(np.matmul(A,inverse_A))
print('---------------------')
print(np.matmul(inverse_A,A))

[[ 3. -5.]
 [-1.  2.]]
---------------------
[[1. 0.]
 [0. 1.]]
---------------------
[[1. 0.]
 [0. 1.]]


# Subspace
---
- A **subspace** of $\mathbb{R}^n$ is <font color=green><b>any collection</b>s</font>, denoted as $S$, of vectors in $\mathbb{R}^n$ such that:
1. The zero vector $\in S$.
2. If $u$ and $v$ $\in S$, then $u+v \in S$.
3. If $u \in S$ and $k$ scalar, then $ku \in S$.

# Span
---
- Recall that a span is any linear combination of the vectors in $S$., this also means that the span is a subspace of $\mathbb{R}^n$.

# Subspaces in Matrices
---
-Let $A$ be a $m$x$n$ matrix:
1. The row space of $A$ is the subspace $row(A)$ of $\mathbb{R}^n$ spaned by the rows of $A$.
2. The column space of $A$ is the subspace $column(A)$ of $\mathbb{R}^n$ spaned by the columns of $A$.
#### Example:
- Given a matrix:
\begin{equation}
A = \begin{bmatrix}
1 & -1 \\
0 & 1 \\
3 & -3 \\
\end{bmatrix}
\end{equation}
- Question 1: is
\begin{equation}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
\end{equation}
a column subspace of $A$?
- Solution: The goal here is to show that the given column is in the column space of $A$, this can be done by showing $\textbf{Ax=b}$ and using row operation to form a reduced echelon.
\begin{equation}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 1 \\
0 & 1 & 2 \\
3 & -3 & 3 \\
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{3}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 1 \\
0 & 1 & 2 \\
1 & -1 & 1 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{3}-\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 1 \\
0 & 1 & 2 \\
0 & 0 & 0 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{1}+\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & 0 & 3 \\
0 & 1 & 2 \\
0 & 0 & 0 \\
\end{array}
\end{bmatrix}
\end{equation}
$\therefore$ We have transformed it into a reduced echelon indicating that 
\begin{equation}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
\end{equation}
is in the column space.
- Question 2: Determine if the row
\begin{equation}
\begin{bmatrix}
4 & 5 
\end{bmatrix}
\end{equation}
- Solution: Determine if we can create a reduced column echelon:
\begin{bmatrix}
A \\
\hline
\textbf{w} \\
\end{bmatrix}
- With this we need to create a reduced column echelon:
\begin{equation}
\begin{bmatrix}
1 & -1 \\
0 & 1 \\
3 & -3 \\
\hline
4 & 5 \\
\end{bmatrix}
\xrightarrow[\text{R}_{4}-4\text{R}_{1}]{\text{R}_{3}-3\text{R}_{1}}
\begin{bmatrix}
1 & -1 \\
0 & 1 \\
0 & 0 \\
\hline
0 & 9 \\
\end{bmatrix}
\end{equation}
- The result shows a proper row echelon, indicating that:
\begin{equation}
\begin{bmatrix}
4 & 5 
\end{bmatrix}
\end{equation}
is part of the row space.
#### Note:
---
- Two matrices, $A$ and $B$, are row equivalent if and only if $row(B)=row(A)$.
- Given a matrix $A$ with size $m$x$n$ and given a homogenous linear system $\textbf{Ax}=0$, The solution sets for $\textbf{Ax}=0$ is also a part of the subspace of $\mathbb{R}^n$.

# The Null Space
---
- Given a matrix $A$ with size $m$x$n$. The null spaec of $A$ is the subspace of $\mathbb(R)^n$ that consist of the solutions to the homogenous linear equation $\textbf{Ax}=0$.
- This is denoted by null($A$)<br>
<font color=red><b>$\to$</b></font>: **Do not confuse this with the null set** $\emptyset$.

# The Basis
---
- The basis is a set of vectors in the subspace, $S$ that has two requirements:<br>
    $\to$ It must span the subspace, $S$.<br>
    $\to$ It must be linearly independent of each other.
#### Example
- Find the basis for the row space of:
\begin{equation}
\begin{bmatrix}
1 & 1 & 3 & 1 & 6 \\
2 & -1 & 0 & 1 & -1 \\
-3 & 2 & 1 & -2 & 1 \\
4 & 1 & 6 & 1 & 3 \\
\end{bmatrix}
\end{equation}<br>
- Solution: Determine the proper row echelon/reduced row echelon:
\begin{equation}
\begin{bmatrix}
1 & 0 & 1 & 0 & -1 \\
0 & 1 & 2 & 0 & 3 \\
0 & 0 & 0 & 1 & 4 \\
0 & 0 & 0 & 0 & 0 \\
\end{bmatrix}
\end{equation}<br>
- The basis are all non-zero rows $[1,0,1,0,-1],[0,1,2,0,3],[0,0,0,1,4]$
### Notes Related to Basis.
---
1. Let $S$ be a subspace in $\mathbb{R}^n$. Then any basis for $S$ must have the same number of vectors.
2. If $S$ be a subspace in $\mathbb{R}^n$. Then the number of vectors in a basis for $S$ is called a **dimension** of $S$, and is denoted by $\textbf{dim(s)}$.
3. The row and the column spaces of matrix $A$ must have the same dimension.
4. The rank of a matrix $A$ is the dimension of its row and columns and is denoted by $\textbf{rank(A)}$.
5. To find the rank of a matrix $A$, use the row operation to transform the matrix into a row echelon form, or in its reduced row echelon form, count the number of rows which are non-zero entries, this is the rank of your matrix.
6. The **nullity** of a matrix $A$ is the dimension of its null space and is denoted ny $\textbf{nullity(A)}$.
7. Given a matrix $A$ when dimension $m$x$n$, $\textbf{rank(A) + nullity(A)}=n$
### Theorems
---
- Let $A$ be a mtrix of size $m$x$n$, then:
1. rank($A^TA$) = rank($A$).
2. The $n$x$n$ matrix $A^TA$ is invertible $\iff$ rank($A$)=n.

# Coordinates
---
- Let $S$ be a subspace of $\mathbb{R}^n$ and let $\beta = \{v_1, v_2, ....,v_k\}$ be a basis for $S$. Let $\textbf{v}$ be a vector in $S$, if we can write $\textbf{v}= c_1v_1+c_2v_2+....+c_nv_n$ then $c_1, c_2, c_3, ....,c_n$ are called the **coordinates of v with respect to** $\beta$.
- The column vector:
\begin{equation}
[\textbf{v}]_{\beta} = 
\begin{bmatrix}
c_1 \\
c_2 \\
c_3 \\
. \\
. \\
. \\
c_n
\end{bmatrix}
\end{equation}
is called the **coordinate vector of v with respect to** $\beta$.
#### Example:
- Given three vectors which are in the same subspace, $S$ of $\mathbb{R}^3$:
\begin{equation}
\textbf{u} =
\begin{bmatrix}
2 \\
-1 \\
5
\end{bmatrix},
\textbf{v} =
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix},
\textbf{w} =
\begin{bmatrix}
0 \\
-5 \\
1
\end{bmatrix}
\end{equation}
<br>
Find the coordinate vector $\textbf{v}$ such that:
$\textbf{w} = \textbf{v}_1\textbf{u}+\textbf{v}_2\textbf{v}$
- Solution: Use the augmented matrix and try to solve for $\textbf{v}_1$ and $\textbf{v}_2$
\begin{equation}
\textbf{v}_1
\begin{bmatrix}
3 \\
-1 \\
5 \\
\end{bmatrix}
+
\textbf{v}_2
\begin{bmatrix}
2 \\
1 \\
3 \\ 
\end{bmatrix} = 
\begin{bmatrix}
0 \\
-5 \\
1 \\
\end{bmatrix}
\end{equation}
<br><br>
\begin{equation}
\begin{bmatrix}
\begin{array}{cc|c}
3 & 2 & 0 \\
-1 & 1 & -5 \\
5 & 3 & 1 \\
\end{array}
\end{bmatrix}
\xrightarrow{-\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cc|c}
3 & 2 & 0 \\
1 & -1 & 5 \\
5 & 3 & 1 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{1}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 5 \\
3 & 2 & 0 \\
5 & 3 & 1 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{3} - 5\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 5 \\
3 & 2 & 0 \\
0 & 8 & -24 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{2} - 3\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 5 \\
0 & 5 & -15 \\
0 & 8 & -24 \\
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{5}\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 5 \\
0 & 1 & -3 \\
0 & 8 & -24 \\
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{8}\text{R}_{3}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 5 \\
0 & 1 & -3 \\
0 & 1 & -3 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & -1 & 5 \\
0 & 1 & -3 \\
0 & 0 & 0 \\
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{bmatrix}
\begin{array}{cc|c}
1 & 0 & 2 \\
0 & 1 & -3 \\
0 & 0 & 0 \\
\end{array}
\end{bmatrix}
\end{equation}
<br><br>
- The constants $c_1 = 2$ and $c_2 = -3$
- $\therefore$ **coordinate vector of v with respect to** $\beta$ is
\begin{equation}
[\textbf{v}]_{\beta} = 
\begin{bmatrix}
c_1 \\
c_2 \\
\end{bmatrix} = 
\begin{bmatrix}
2 \\
3 \\
\end{bmatrix}
\end{equation}

# <font color=red> CODE CHALLENGES </font>
---
### Instruction
1. Push your solutions to your github account.
3. Deadline is before finals.
---
1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.
2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.
3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.
4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.
5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

# <font color=red> Problem Solving </font>
---
Instructions
1. Write your solution in latex.
2. Push your solutions to your github account.
3. Deadline is before finals.
---
1. Solve $X$ given that:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix},
B =
\begin{bmatrix}
-1 & 0 \\
1 & 1 \\
\end{bmatrix}
\end{equation}
- $3X = A-2B$
- $2(A-B+2X) = 3(X-B)$
<br>
<br>
2. Write $B$ as a linear combination of the other matrices, if possible.
- 
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 2 \\
-1 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
2 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
<br><br>
- 
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix},
A_3 =
\begin{bmatrix}
1 & -1 \\
1 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
<br>
<br>
3. Given the following:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
2 & 6 \\
\end{bmatrix},
b_1 =
\begin{bmatrix}
3 \\
5 \\
\end{bmatrix},
b_2 =
\begin{bmatrix}
-1 \\
2 \\
\end{bmatrix},
b_3 =
\begin{bmatrix}
2 \\
0 \\
\end{bmatrix}
\end{equation}
- Find $A^{-1}$, and use this to solve for $Ax=b_1,Ax=b_2,Ax=b_3$
- Solve all three linear systems by row reducing the augmented matrix:
\begin{equation}
\begin{bmatrix}
\begin{array}{c|ccc}
A &
b_1 &
b_2 &
b_3 \\
\end{array}
\end{bmatrix}
\end{equation}
4. In each given, determine if $b$ in in $col(A)$, and $w$ is in $row(A)$
- 
\begin{equation}
A =
\begin{bmatrix}
1 & 0 & -1 \\
1 & 1 & 1 \\
\end{bmatrix},
b =
\begin{bmatrix}
3 \\
2 \\
\end{bmatrix},
w =
\begin{bmatrix}
-1 &
1 &
1
\end{bmatrix},
\end{equation}
- 
\begin{equation}
A =
\begin{bmatrix}
1 & 1 & -1 \\
1 & 3 & 0 \\
3 & -1 & -5 \\
\end{bmatrix},
b =
\begin{bmatrix}
1 \\
2 \\
1 \\
\end{bmatrix},
w =
\begin{bmatrix}
1 &
-3 &
-3
\end{bmatrix},
\end{equation}
5. Find the rank and nullity of:
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
6 & 3 & 5 & 1 & 0 \\
1 & 0 & 2 & 2 & 5 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix},